services:
  ERPLibre:
    image: odoo:18
    ports:
      - 8070:8069
      - 8073:8071
      - 8074:8072
    environment:
      HOST: db
      PASSWORD: mysecretpassword
      USER: odoo
      POSTGRES_DB: postgres
      STOP_BEFORE_INIT: "False"
      DB_NAME: ""
      UPDATE_ALL_DB: "False"
    depends_on:
      - db
    # not behind a proxy
    #command: odoo --workers 0
    # behind a proxy
    #command: odoo --workers 2 --proxy-mode
    # For production ready
    #command: odoo --workers 2 --proxy-mode --no-database-list
    command: odoo
    volumes:
      # See the volume section at the end of the file
      - erplibre_data_dir_v18:/var/lib/odoo
      - ./addons:/mnt/extra-addons:ro
      - erplibre_conf_v18:/etc/odoo
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - erplibre-db-data-v18:/var/lib/postgresql/data/pgdata
    restart: always

# We configure volume without specific destination to let docker manage it. To configure it through docker use (read related documentation before continuing) :
# - docker volume --help
# - docker-compose down --help
volumes:
  erplibre_data_dir_v18:
  erplibre_conf_v18:
  erplibre-db-data-v18:
